In [23]:
import os 
import numpy
xyz_location = os.path.join('data','water.xyz')
xyz_file = numpy.genfromtxt(fname=xyz_location, skip_header=2, dtype='unicode')
symbols=xyz_file[:,0]
coordinates=xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)
print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [28]:
def calculate_distance(atom1,atom2):
    x_distance = atomA[0]-atomB[0]
    y_distance = atomA[1]-atomB[1]
    z_distance = atomA[2]-atomB[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [53]:
def bond_check(bond_distance,minimum_value=0,maximum_value=1.5): #Equals set the defaults, anything without equals user must spec
    if bond_distance>minimum_value and bond_distance<maximum_value:
        return True
    else:
        return False

In [54]:
for numA, atomA in enumerate(coordinates):
    for numB, atomB in enumerate(coordinates):
        if numB<numA:
            distance_AB = calculate_distance(atomA, atomB)
            if bond_check(distance_AB,0,1.5):
                print(F'{symbols[numA]} to {symbols[numB]}: {distance_AB:.3f}')

H1 to O: 0.969
H2 to O: 0.969


In [21]:
cd ..

C:\Users\baj0040\Desktop\Setca


In [26]:
def function_name(paramaters): #paramaters are the variables that are given and modified by code, then calc value to return
    #lines of code
    #lines of code
    return value_to_return